import Navigation from '@/app/(Components)/Navigation'
import './globals.css'
import '@/app/(styles)/navigation.css'
import '@/app/(styles)/home.css'
import { AppContexProvider } from './contex/store'

export const metadata = {
  title: 'The Code Hurdle Podcast',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppContexProvider>
          <Navigation />
        {children}
        </AppContexProvider>
        </body>
    </html>
  )
}
